### ISSUE TITLE
Add method to minimise marker concern

### ISSUE THREAD

**Issue by hannahb1024** [hannahb1024/uob-sepp-prototype#24]
As per discussion in meeting:
Methods will return decimal offset values that will be applied to a poor markers marks, to minimise their deviation compared to either exemplary markers or to all markers averaged.

**Comment by hannahb1024** [comment]
@grumpman Having issue implementing this - as I originally understood was to use hill climb to minimise average difference, but the tests marked list length on the example data is 20, but the lengths for the exemplary marker and the all markers is 10. They also don't contain scores but instead decimal values. Where can I get the scores to normalise against, or have I misunderstood the intended method implementation entirely?

**Comment by grumpman** [comment]
The objective is to find an optimal amount to increase/decrease all of a markers scores by, so that when running the chi-squared test on either the expected result based on all scores or the expected result based on exemplary markers scores it is in the "green zone". For the prototype this "green zone" is 13.442 - if it is great than this number it means there's a 20% chance of the marker is following the distribution.

To do this first you need to extract all of the scores from the selected markers marked_test list into a num list. There is a function I made: getAllScores(<list of TestResult objects>) which will return a number list for you. 
Then increase/decrease all of these scores by a certain amount (you will have to right a function to do this), followed by re-binning the list of scores. This can be done using the constructer of the binned_data class.
Finally chi-squared test the markers new binned scores against the unchanged expected result scores to get the new chi-squared value.

Using this value and the previous ones you will then need to decide whether to increase or decrease the marks before running the algorithm again or to return the amount you have increased/decreased all scores by.

Hope this helps if you have any more questions comment again or message me on discord!

**Comment by hannahb1024** [comment]
Thanks for your explanation - very clear and helpful. Will send a PR soon. Have set the algorithm to step by 2 marks each time as a placeholder - do let me know your thoughts on how much you'd like it to step by each time on the hill climb.
